### ISSUE TITLE
Add `tmp` dir to the .npmignore.

### ISSUE THREAD

**Issue by stefanpenner** [RSSchermer/ember-spinner-button#1]
https://github.com/ember-cli/ember-cli/issues/4199

like: https://github.com/ember-cli/ember-cli/commit/6ac18227ea571988fa9d9950e9a1051fdd990c7c

**Comment by RSSchermer** [comment]
Thanks for the heads up. `tmp/` was already in .npmignore though, so I don't think its a problem for this addon. There's also ivanvanderbyl/ember-spin-button though and that one did appear in ember-cli/ember-cli#4199 OP's list.
